# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personalpage.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_personalpage(object):
    def setupUi(self, personalpage):
        personalpage.setObjectName(_fromUtf8("personalpage"))
        personalpage.resize(800, 600)
        self.rechargeButton = QtGui.QPushButton(personalpage)
        self.rechargeButton.setGeometry(QtCore.QRect(640, 150, 121, 41))
        self.rechargeButton.setObjectName(_fromUtf8("rechargeButton"))
        self.rentAdd = QtGui.QPushButton(personalpage)
        self.rentAdd.setGeometry(QtCore.QRect(390, 440, 121, 41))
        self.rentAdd.setObjectName(_fromUtf8("rentAdd"))
        self.label_11 = QtGui.QLabel(personalpage)
        self.label_11.setGeometry(QtCore.QRect(160, 90, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_4 = QtGui.QLabel(personalpage)
        self.label_4.setGeometry(QtCore.QRect(90, 230, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.sentButton = QtGui.QPushButton(personalpage)
        self.sentButton.setGeometry(QtCore.QRect(640, 60, 121, 41))
        self.sentButton.setObjectName(_fromUtf8("sentButton"))
        self.Add = QtGui.QPushButton(personalpage)
        self.Add.setGeometry(QtCore.QRect(400, 240, 121, 41))
        self.Add.setObjectName(_fromUtf8("Add"))
        self.label = QtGui.QLabel(personalpage)
        self.label.setGeometry(QtCore.QRect(10, 30, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(personalpage)
        self.label_3.setGeometry(QtCore.QRect(90, 180, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_8 = QtGui.QLabel(personalpage)
        self.label_8.setGeometry(QtCore.QRect(20, 90, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_2 = QtGui.QLabel(personalpage)
        self.label_2.setGeometry(QtCore.QRect(430, 30, 141, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.username = QtGui.QLabel(personalpage)
        self.username.setGeometry(QtCore.QRect(170, 30, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.username.setFont(font)
        self.username.setText(_fromUtf8(""))
        self.username.setAlignment(QtCore.Qt.AlignCenter)
        self.username.setObjectName(_fromUtf8("username"))
        self.message = QtGui.QTextEdit(personalpage)
        self.message.setGeometry(QtCore.QRect(550, 290, 211, 121))
        self.message.setObjectName(_fromUtf8("message"))
        self.text = QtGui.QTextEdit(personalpage)
        self.text.setGeometry(QtCore.QRect(430, 50, 191, 61))
        self.text.setObjectName(_fromUtf8("text"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(personalpage)
        self.doubleSpinBox.setGeometry(QtCore.QRect(470, 150, 131, 31))
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.lineEdit = QtGui.QLineEdit(personalpage)
        self.lineEdit.setGeometry(QtCore.QRect(180, 190, 181, 31))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(personalpage)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 240, 181, 31))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(personalpage)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 290, 181, 31))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_7 = QtGui.QLabel(personalpage)
        self.label_7.setGeometry(QtCore.QRect(20, 280, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_4 = QtGui.QLineEdit(personalpage)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 400, 181, 31))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(personalpage)
        self.lineEdit_5.setGeometry(QtCore.QRect(170, 450, 181, 31))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.label_5 = QtGui.QLabel(personalpage)
        self.label_5.setGeometry(QtCore.QRect(80, 440, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(personalpage)
        self.label_6.setGeometry(QtCore.QRect(80, 390, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_6 = QtGui.QLineEdit(personalpage)
        self.lineEdit_6.setGeometry(QtCore.QRect(170, 500, 181, 31))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.label_9 = QtGui.QLabel(personalpage)
        self.label_9.setGeometry(QtCore.QRect(10, 490, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(personalpage)
        self.label_10.setGeometry(QtCore.QRect(20, 140, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_12 = QtGui.QLabel(personalpage)
        self.label_12.setGeometry(QtCore.QRect(10, 350, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))

        self.retranslateUi(personalpage)
        QtCore.QMetaObject.connectSlotsByName(personalpage)

    def retranslateUi(self, personalpage):
        personalpage.setWindowTitle(_translate("personalpage", "personal page", None))
        self.rechargeButton.setText(_translate("personalpage", "Recharge", None))
        self.rentAdd.setText(_translate("personalpage", "Add", None))
        self.label_4.setText(_translate("personalpage", "Price : ", None))
        self.sentButton.setText(_translate("personalpage", "SENT", None))
        self.Add.setText(_translate("personalpage", "Add", None))
        self.label.setText(_translate("personalpage", "Username : ", None))
        self.label_3.setText(_translate("personalpage", "Item : ", None))
        self.label_8.setText(_translate("personalpage", "Balance : ", None))
        self.label_2.setText(_translate("personalpage", "Sent message to Superuser:", None))
        self.label_7.setText(_translate("personalpage", "Description:", None))
        self.label_5.setText(_translate("personalpage", "Price : ", None))
        self.label_6.setText(_translate("personalpage", "Item : ", None))
        self.label_9.setText(_translate("personalpage", "Description:", None))
        self.label_10.setText(_translate("personalpage", "SELL/BID", None))
        self.label_12.setText(_translate("personalpage", "RENT", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    personalpage = QtGui.QWidget()
    ui = Ui_personalpage()
    ui.setupUi(personalpage)
    personalpage.show()
    sys.exit(app.exec_())

